### ISSUE TITLE
Generate solution on disk instead of rendering on the screen

### ISSUE THREAD

**Issue by gtw123** [gtw123/OpusSolver#2]
It currently takes a long time to render the instructions on the screen, and for large puzzles it will eventually get out of sync with the game and fail. A simpler and faster way would be to make it generate a solution file on disk instead. See https://www.reddit.com/r/opus_magnum/comments/8q0asl/i_made_a_bot_to_solve_puzzles_for_me/e0gfyky/

**Comment by flexagontnt** [comment]
I am not sure how to use fazzone's solution file encoder/decoder.

**Comment by gtw123** [comment]
v2 now reads .puzzle files and writes .solution files instead of analysing the screen and simulating mouse/keyboard input.
