### ISSUE TITLE
Bot unable to detect Glyph of Disposal

### ISSUE THREAD

**Issue by flexagontnt** [gtw123/OpusSolver#5]
I don't know why the bot won't do the puzzle "Embalming Fluid". An error says it can't identify a glyph.

**Comment by gtw123** [comment]
Fixed now.

The problem is that the sidebar "fades out" at the bottom, and the fix I applied yesterday for small screens wasn't quite accounting for that.

**Comment by 837951602** [comment]
How does it matter? Bot can move unused atom far away
